server:
  port: 8094
  
               
# Conexión a MySQL

spring:
  security:
    user:
         name: admin
         password: $2y$12$VgUpmiD7zZER24TK6dZch.22bKxsZMz8ukQ36HISgis4cHxZq4XQG



# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka