server:
  port: 80

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
# Mapeo de Microservicios
 
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: id-students
        uri: http://localhost:8090/lista/students
        predicates:
        - Path=/lista/students
        
      - id: id-course
        uri: http://localhost:8091/lista/courses
        predicates:
        - Path=/lista/courses
        
      - id: id-profesor
        uri: http://localhost:8092/lista/profesor
        predicates:
        - Path=/lista/profesor
        
      - id: id-course-detail
        uri: http://localhost:8093/lista/cursodetalle
        predicates:
        - Path=/lista/cursodetalle  
        
      - id: albums
        uri: https://jsonplaceholder.typicode.com/albums
        predicates:
        - Path=/albums       
# Activacion de endpoints         
#management:
#     endpoints:
#       web:
#         exposure:
#           include: '*'
#     endpoint:
#       health:
#         show-details: always

management:
   endpoint:
     gateway:
       enabled: true
   endpoints:
     web:
       exposure:
         include: "gateway"
